[[entries]]
title = "これは何？"

  [[entries.entries]]
  title = "500mLのウェブサイトです。"

[[entries]]
title = "お前は誰？"
  [[entries.entries]]
  title = "500mLです。"
  url = "about"

[[entries]]
title = "全ての投稿"

  [entries.post_list]
  limit = 5
  show_more = true
  show_more_text = "過去の投稿を見る"
  show_more_url = "posts"

[[entries]]
title = "RSS"
url = "index.xml"

[[entries]]
title = "リンク集"
url = "links"